name: Build Executables

permissions:
    contents: write

on:
  release:
    types: [created]

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pandas openpyxl pillow pyinstaller

      - name: Build Windows exe
        run: |
          pyinstaller --clean --onefile --windowed main.py

      - name: Upload Windows Artifact
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: dist/main.exe
            asset_name: SpiideoStatsApp-Windows.exe
            asset_content_type: application/octet-stream

  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pandas openpyxl pillow pyinstaller

      - name: Build Mac app
        run: |
          pyinstaller --clean --windowed main.py

      - name: Zip Mac App
        run: |
          cd dist
          zip -r SpiideoStatsApp-Mac.zip main.app

      - name: Upload Mac Artifact
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: dist/SpiideoStatsApp-Mac.zip
            asset_name: SpiideoStatsApp-Mac.zip
            asset_content_type: application/zip